config/routes.rb
Rails.application.routes.draw do
  root 'activities#index'

  resources :activities, except: [:index]
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  size        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Activity < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.order(created_at: :desc)
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      flash[:success] = 'Activity has beed added sucessfully'
      # new request 
      redirect_to activity_path(@activity)
    else
      flash[:failure] = 'Activity has not been added'
      # same request, but updated template, params stay the same
      render :new
    end
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])

    if @activity.update(activity_params)
      flash[:success] = 'Activity has beed updated sucessfully'
      redirect_to activity_path(@activity)
    else
      flash[:failure] = 'Activity has not been updated'
      render :edit
    end
  end

  def destroy
    debugger
    @activity = Activity.find(params[:id])

    if @activity.destroy
      flash[:success] = 'Activity has beed deleted sucessfully'
      redirect_to root_path
    else
      flash[:failure] = 'Activity has not been deleted'
      render activity_path(@activity)
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :description, :value, :size)
  end
end
pp

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_form.html.erb
<%= form_with model: @activity do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :size %><br>
    <%= form.text_field :size %>
  </div>

  <div>
    <%= form.label :value %><br>
    <%= form.text_field :value %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Edit activity</h1>

<%= render 'form', activity: @activity %>

app/views/activities/index.html.erb
<h1>Activities</h1>

<%= link_to 'New activity', new_activity_path %>

<ul>
  <% @activities.each do |activity| %>
    <li>
      <%= link_to activity.name, activity_path(activity.id) %>
      <%= activity.value %>
    </li>
  <% end %>
</ul>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= form_with model: @activity do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :size %><br>
    <%= form.text_field :size %>
  </div>

  <div>
    <%= form.label :value %><br>
    <%= form.text_field :value %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/show.html.erb
<h1>Activity <%= @activity.id %></h1>

<article>
  <h1>
    <%= @activity.value %>
  </h1>
  <p>
    <%= @activity.description %>
  </p>
  <p>
    <%= @activity.value %>, <%= @activity.size %>, <%= @activity.created_at.in_time_zone('Warsaw').strftime("%H:%m %d.%m, %Y") %>
  </p>
</article>

<%= link_to 'Edit', edit_activity_path(@activity) %>
<%= link_to 'Delete', activity_path(@activity), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %>
<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MindfulnessApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% if flash[:success] %>
      <p class="flash"><%= flash[:success] %></p>
    <% end %>
  </body>
</html>